server:
  port: 8090

spring:
  application:
    name: workload-service

  datasource:
    url: jdbc:h2:mem:workloadDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  pattern:
    level: "%5p [%X{txId:-no-tx}]"